### ISSUE TITLE
Uploaded src folder no change to knomi?

### ISSUE THREAD

**Issue by LTSpenny** [ZISQO/BTT_Knomi_custom_theme#1]
Hi. Followed instructions of copying src folder into src folder for firmware, built using vstudio and uploaded to knomi but receive no change in graphics of knomi. Any troubleshooting tips?

i was able to convert a gif to work with knomi. Its very size specific as to how much flash memory is on the unit. So i know it should be working. However i dont know how to verify what the images or gifs are supposed to look like while on a .c format. Is there a way to view them other than uploading to knomi?

**Comment by ZISQO** [comment]
Sorry, I uploaded the file by mistake, now before building the upload, the new version of the .c file must be the same size or smaller than the original .c file to avoid firmware upload problems (large files are difficult due to the Knomi's small flash capacity).
