### ISSUE TITLE
I get an error when compiling.

### ISSUE THREAD

**Issue by ByMalicious** [ZISQO/BTT_Knomi_custom_theme#3]
![image](https://github.com/ZISQO/BTT_Knomi_custom_theme/assets/41118490/3d827ea4-0be3-4d3d-8987-d2889de53db2)

What is problem ?

**Comment by ZISQO** [comment]
> ![image](https://private-user-images.githubusercontent.com/41118490/286421410-3d827ea4-0be3-4d3d-8987-d2889de53db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzE5NjcsIm5iZiI6MTcxNzkzMTY2NywicGF0aCI6Ii80MTExODQ5MC8yODY0MjE0MTAtM2Q4MjdlYTQtMGJlMy00ZDNkLTg5ODctZDI4ODlkZTUzZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDExMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDY5OGFhZjVhNWE3MTQ0MjkwZGVlNDBlODgzMjU5ZmJjMzdlMTM0NzAwM2MwODM4MTY4NDQ3NmEyZjI0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0u3f6e-RvRzEGXNxQqEbY5y_9HW9qBBgsV37XxV1kmw)
> 
> What is problem ?

---- 

so sorry to late my feed back, so just looking yellow text first!! verifying your build location. 🍡 
also your location was it on OneDrive it meant not cloud service location it must be local location of your diskdrive.
